### ISSUE TITLE
damn

### ISSUE THREAD

**Issue by usercybe** [xxxOMA/MonsoonRip#3]
nothing against you or quick, but damn quick really messed up

**Comment by quickdaffy** [comment]
yeah no shit, i gave the source to someone who wanted to “rat 5000 kids” and is on the official skid list
https://github.com/XatzClient/official-skid-list

**Comment by xxxOMA** [comment]
you're actually retarded lol, I've told you many times that that skid list is made by a retard who is responsible for every ratted stolfo crack, it's actually funny you ignore this everytime and say that I "ratted 5000 kids!1!111" everytime you don't have a response to an argument. You're actually brain damaged, it's so funny. Keep crying.
